# Generated by Django 4.2.16 on 2024-09-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.PositiveSmallIntegerField()),
                ('passing_game', models.IntegerField()),
                ('flying_ball', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('ball_control', models.PositiveIntegerField()),
                ('group_defense', models.PositiveIntegerField()),
                ('completion_of_action', models.IntegerField()),
                ('team_attack', models.IntegerField(default=0)),
            ],
        ),
    ]
